# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Yarn
      run: npm i -g yarn
    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Build binary
      run: yarn run build:nocache --filter=./packages/overlay
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: |
          packages/overlay/out/FoxFall Overlay/win/FoxFall-2.4.1-win-x64.exe
          packages/overlay/out/FoxFall Overlay/win/FoxFall-2.4.1-win-x64.exe.blockmap
          packages/overlay/out/FoxFall Overlay/win/latest.yml
